[global]
packages=default

skip=rules.ini
skip=bash
skip=bin
skip=dconf
skip=etc/profile.d
skip=git
skip=packages
skip=tmux
skip=vim

# needs to be copied instead of symlinked:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067002
skip=etc/plymouth/plymouthd.conf

### role definitions ###################################################

[role "desktop"]
packages=desktop

link=/chromium/
link=/fwupd/
link=/gtk/
link=/mise/

link=etc/kernel
link=etc/NetworkManager
link=etc/pipewire
link=etc/security
link=etc/tuned
link=etc/udev
link=etc/wireplumber
link=etc/xdg

link=config/alacritty
link=config/autostart
link=config/fontconfig
link=config/ghostty
link=config/mpv
link=config/systemd/user
link=config/wezterm
link=config/yt-dlp
link=local/share/applications
link=local/share/flatpak
link=local/share/fonts
link=local/share/themes
link=mozilla

[role "development"]
packages=development
link=/epmd/

[role "audio"]
packages=audio
link=/com.bitwig.BitwigStudio/
link=/io.github.dagargo.Overwitch/

[role "gaming"]
packages=gaming

[role "htpc"]
packages=htpc

link=etc/pipewire/client.conf.d/upmix.conf

link=/kodi/
link=/filebot/

[role "qemu"]
packages=qemu

[role "server"]

### host definitions ###################################################

[host "ocelot"]
role=desktop
role=development
role=audio
role=gaming
role=qemu

link=etc/rtirq.conf
link=etc/pipewire/pipewire.conf.d/tascam-model12.conf

[host "meerkat"]
role=desktop
role=development
role=gaming

[host "schtube"]
role=desktop
role=htpc
role=development
role=gaming

[host "snafu"]
role=server

[host "steamdeck"]
packages=steamdeck
link=/steamdeck/
skip=/.*/
