#!/bin/bash

. /etc/profile.d/001-environment.sh

if [ -z "$SSH_AUTH_SOCK" ]; then
  # Try to connect to a running SSH agent
  socket=`ls -t /tmp/ssh-*/agent.[0-9]* 2>/dev/null | head -1`
  if [ -S "$socket" -a -O "$socket" ]; then
    export SSH_AUTH_SOCK="$socket"
    export SSH_AGENT_PID=${SSH_AUTH_SOCK##*.}
  fi
fi
