# skip: playback-history

[/]
action-double-click='none'
action-hover='none'
action-left-click='toggle_menu'
action-middle-click='play_pause'
action-right-click='open_app'
border-radius=8
custom-bg-color='0,0,0'
dock-position=0
enable-lyrics=false
enable-scroll-controls=false
enable-shadow=true
enable-transparency=false
hide-default-player=true
hide-text=false
inline-artist=true
invert-scroll-animation=false
panel-art-size=22
panel-pill-width=400
pill-dynamic-width=true
popup-custom-width=360
popup-hide-pill-visualizer=false
popup-show-album-title=true
popup-show-vinyl=true
popup-show-visualizer=false
popup-vinyl-rotate=false
popup-vinyl-square=true
position-mode=1
scroll-text=false
shadow-blur=8
shadow-opacity=15
show-album-art=true
show-pill-border=true
tablet-mode=false
target-container=3
transparency-art=false
transparency-strength=50
transparency-text=false
transparency-vis=false
use-custom-colors=false
visualizer-padding=12
visualizer-style=0
