#!/bin/bash

cd `dirname "$0"` || exit 1

echo
for dir in *; do
  if [ -d "$dir" ]; then
    pushd "$dir" >/dev/null

    if [ -d .git ]; then
      cmd="git pull"
    elif [ -d .hg ]; then
      cmd="hg pull"
    elif [ -d .svn ]; then
      cmd="svn update"
    else
      unset cmd
    fi

    if [ -n "$cmd" ]; then
      echo " [1;34m*[0m Updating [1m$dir[0m:"
      $cmd
      echo
    else
      echo " [1;31m%-20s[0m No repository found\n" $dir
      echo
    fi

    popd >/dev/null
  fi
done
