if !has('gui_running')
  finish
endif

" General Settings
" {{{

  set nomousehide

  " disable bash prompt
  let $PROMPT_COMMAND=""

  " selection behaviour
  set selectmode=key
  set selection=inclusive
  set keymodel=startsel
  set mousemodel=extend

" }}}

" Display Settings
" {{{

  " interface
  set guioptions=aigM " disable toolbars, menus, scrollbars
  set guicursor+=a:blinkon0 " disable cursor blinking
  set visualbell t_vb= " disable bells, reset when starting GUI

  " don't use autoselect on OS X
  if has('mac')
    set guioptions-=a
  endif

  if !exists('s:gui_loaded')
    let s:gui_loaded = 1

    set lines=60
    set columns=120

    " font
    if has('mac')
      set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h13
    elseif has('unix')
      if hostname() == 'schtube'
        set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 18
        set lines=28
        set columns=80
      else
        set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 9
      endif
    else
      set guifont=DejaVu_Sans_Mono_for_Powerline:h9:cANSI
    endif

    if &diff
      let &columns = float2nr(&columns * 1.7)
    endif
  endif

" }}}

" Keybindings
" {{{

  " don't use Alt for menus
  set winaltkeys=no

" }}}
