#!/bin/bash

[ "$1" != "--really" ] || exec nice ionice -c3 "$0" --really

HOSTNAME=$( hostname -s )
BACKUP="/slack/backups/$HOSTNAME"

mkdir -p "$BACKUP" || exit 1

for file in /etc/backup.d/*; do
  if [ -x "$file" ]; then
    . "$file"
  fi
done

(date -Iseconds; echo; dpkg --get-selections) > "$BACKUP/packages.txt"
