local wezterm = require 'wezterm'
local config = wezterm.config_builder()
local action = wezterm.action

config.hide_tab_bar_if_only_one_tab = true
config.scrollback_lines = 10000
config.window_background_opacity = 0.85

config.window_padding = {
  left = 0,
  right = 0,
  top = 0,
  bottom = 0,
}

config.colors = {
  foreground = 'white',
  background = 'black',
  cursor_bg = 'white',
  cursor_border = 'white',
  selection_fg = 'black',
  selection_bg = '#fdd',
  visual_bell = '#545652',

  ansi = {
    '#000000',
    '#FF4040',
    '#4D9A05',
    '#C3A000',
    '#417FCF',
    '#8E6199',
    '#05979A',
    '#D3D6CF',
  },

  brights = {
    '#545652',
    '#FF4040',
    '#89E234',
    '#FBE84F',
    '#82B1FF',
    '#AC7EA8',
    '#34E2E2',
    '#EDEDEB'
  },
}

config.visual_bell = {
  fade_in_duration_ms = 50,
  fade_out_duration_ms = 75,
}

config.keys = {
  { key = 'Tab', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'Tab', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'Enter', mods = 'ALT', action = action.ToggleFullScreen },
  { key = '!', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '!', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '\"', mods = 'ALT|CTRL', action = action.DisableDefaultAssignment },
  { key = '\"', mods = 'SHIFT|ALT|CTRL', action = action.DisableDefaultAssignment },
  { key = '#', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '#', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '$', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '$', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '%', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '%', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '%', mods = 'ALT|CTRL', action = action.DisableDefaultAssignment },
  { key = '%', mods = 'SHIFT|ALT|CTRL', action = action.DisableDefaultAssignment },
  { key = '&', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '&', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '\'', mods = 'SHIFT|ALT|CTRL', action = action.DisableDefaultAssignment },
  { key = '(', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '(', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = ')', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = ')', mods = 'SHIFT|CTRL', action = action.ResetFontSize },
  { key = '*', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '*', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '+', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '+', mods = 'SHIFT|CTRL', action = action.IncreaseFontSize },
  { key = '-', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '-', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '-', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '0', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '0', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '0', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '1', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '1', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '2', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '2', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '3', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '3', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '4', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '4', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '5', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '5', mods = 'SHIFT|ALT|CTRL', action = action.DisableDefaultAssignment },
  { key = '5', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '6', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '6', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '7', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '7', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '8', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '8', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '9', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '9', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '=', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '=', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '=', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '@', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '@', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'C', mods = 'CTRL', action = action.CopyTo 'Clipboard' },
  { key = 'C', mods = 'SHIFT|CTRL', action = action.CopyTo 'Clipboard' },
  { key = 'F', mods = 'CTRL', action = action.Search 'CurrentSelectionOrEmptyString' },
  { key = 'F', mods = 'SHIFT|CTRL', action = action.Search 'CurrentSelectionOrEmptyString' },
  { key = 'K', mods = 'CTRL', action = action.ClearScrollback 'ScrollbackOnly' },
  { key = 'K', mods = 'SHIFT|CTRL', action = action.ClearScrollback 'ScrollbackOnly' },
  { key = 'L', mods = 'CTRL', action = action.ShowDebugOverlay },
  { key = 'L', mods = 'SHIFT|CTRL', action = action.ShowDebugOverlay },
  { key = 'M', mods = 'CTRL', action = action.Hide },
  { key = 'M', mods = 'SHIFT|CTRL', action = action.Hide },
  { key = 'N', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'N', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'P', mods = 'CTRL', action = action.ActivateCommandPalette },
  { key = 'P', mods = 'SHIFT|CTRL', action = action.ActivateCommandPalette },
  { key = 'R', mods = 'CTRL', action = action.ReloadConfiguration },
  { key = 'R', mods = 'SHIFT|CTRL', action = action.ReloadConfiguration },
  { key = 'T', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'T', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'U', mods = 'CTRL', action = action.CharSelect{ copy_on_select = true, copy_to =  'ClipboardAndPrimarySelection' } },
  { key = 'U', mods = 'SHIFT|CTRL', action = action.CharSelect{ copy_on_select = true, copy_to =  'ClipboardAndPrimarySelection' } },
  { key = 'V', mods = 'CTRL', action = action.PasteFrom 'Clipboard' },
  { key = 'V', mods = 'SHIFT|CTRL', action = action.PasteFrom 'Clipboard' },
  { key = 'W', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'W', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'X', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'X', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'Z', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'Z', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '[', mods = 'SHIFT|SUPER', action = action.DisableDefaultAssignment },
  { key = ']', mods = 'SHIFT|SUPER', action = action.DisableDefaultAssignment },
  { key = '^', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '^', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '_', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = '_', mods = 'SHIFT|CTRL', action = action.DecreaseFontSize },
  { key = 'c', mods = 'SHIFT|CTRL', action = action.CopyTo 'Clipboard' },
  { key = 'c', mods = 'SUPER', action = action.CopyTo 'Clipboard' },
  { key = 'f', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'f', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = 'k', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'k', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = 'l', mods = 'SHIFT|CTRL', action = action.ShowDebugOverlay },
  { key = 'm', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'm', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = 'n', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'n', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = 'p', mods = 'SHIFT|CTRL', action = action.ActivateCommandPalette },
  { key = 'r', mods = 'SHIFT|CTRL', action = action.ReloadConfiguration },
  { key = 'r', mods = 'SUPER', action = action.ReloadConfiguration },
  { key = 't', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 't', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = 'u', mods = 'SHIFT|CTRL', action = action.CharSelect{ copy_on_select = true, copy_to =  'ClipboardAndPrimarySelection' } },
  { key = 'v', mods = 'SHIFT|CTRL', action = action.PasteFrom 'Clipboard' },
  { key = 'v', mods = 'SUPER', action = action.PasteFrom 'Clipboard' },
  { key = 'w', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'w', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = 'x', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'z', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = '{', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '{', mods = 'SHIFT|SUPER', action = action.DisableDefaultAssignment },
  { key = '}', mods = 'SUPER', action = action.DisableDefaultAssignment },
  { key = '}', mods = 'SHIFT|SUPER', action = action.DisableDefaultAssignment },
  { key = 'phys:Space', mods = 'SHIFT|CTRL', action = action.QuickSelect },
  { key = 'PageUp', mods = 'SHIFT', action = action.ScrollByPage(-1) },
  { key = 'PageUp', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'PageUp', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'PageDown', mods = 'SHIFT', action = action.ScrollByPage(1) },
  { key = 'PageDown', mods = 'CTRL', action = action.DisableDefaultAssignment },
  { key = 'PageDown', mods = 'SHIFT|CTRL', action = action.DisableDefaultAssignment },
  { key = 'LeftArrow', mods = 'SHIFT|CTRL', action = action.ActivatePaneDirection 'Left' },
  { key = 'LeftArrow', mods = 'SHIFT|ALT|CTRL', action = action.AdjustPaneSize{ 'Left', 1 } },
  { key = 'RightArrow', mods = 'SHIFT|CTRL', action = action.ActivatePaneDirection 'Right' },
  { key = 'RightArrow', mods = 'SHIFT|ALT|CTRL', action = action.AdjustPaneSize{ 'Right', 1 } },
  { key = 'UpArrow', mods = 'SHIFT|CTRL', action = action.ActivatePaneDirection 'Up' },
  { key = 'UpArrow', mods = 'SHIFT|ALT|CTRL', action = action.AdjustPaneSize{ 'Up', 1 } },
  { key = 'DownArrow', mods = 'SHIFT|CTRL', action = action.ActivatePaneDirection 'Down' },
  { key = 'DownArrow', mods = 'SHIFT|ALT|CTRL', action = action.AdjustPaneSize{ 'Down', 1 } },
  { key = 'Insert', mods = 'SHIFT', action = action.PasteFrom 'PrimarySelection' },
  { key = 'Insert', mods = 'CTRL', action = action.CopyTo 'PrimarySelection' },
  { key = 'Copy', mods = 'NONE', action = action.CopyTo 'Clipboard' },
  { key = 'Paste', mods = 'NONE', action = action.PasteFrom 'Clipboard' },
}

return config
