#!/bin/sh -e
#
#    users: print the number of remote users on the machine
#
#    Copyright (C) 2009 Raphaël Pinson.
#    Copyright (C) 2009 Canonical Ltd.
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Raphaël Pinson <raphink@ubuntu.com>
#             Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__users_detail() {
	ps -ef | grep "sshd;.*@" | grep -v grep
}

__users() {
	local console=`who | egrep " (console|tty[0-9])" | wc -l`
	local users="users"
	[ $console -eq 1 ] && users="user"
	[ $console -gt 0 ] && printf "$(color b y k)%d$(color -)$(color y k) $users$(color -) " $console

	local remote=`pgrep -f "sshd:.*@" | wc -l`
	local users="users"
	[ $remote -eq 1 ] && users="user"
	[ $remote -gt 0 ] && printf "$(color b Y k)%d$(color -)$(color Y k) remote $users$(color -) " $remote
}

# vi: syntax=sh ts=4 noexpandtab
