#!/bin/bash

tmux copy-mode

function search {
  tmux send-keys -X search-backward "$1"
}

case "$1" in
  # freeform search
  "") tmux send-keys "?";;

  paths)
    path='[-_.[:alnum:]]';
    search "~?(/$path+|$path+/|$path*\.$path+)+$path*(:[0-9]+)*"
    ;;

  prompts)
    search ".*𝝺.*"
    ;;

  quotes)
    search "('[^']+'|\"[^\"]+\")"
    ;;

  # interesting things (URLs, emails, hashes, IPs)
  interesting)
    urls='\b(https?://|git@|git://|ssh://|ftp://|file:///)[[:alnum:]?=%/_.:,;~@!#$&()*+-]*'
    emails='\b[-_\.[:alnum:]]+@[-_\.[:alnum:]]+\b'
    hashes='\b(([0-9a-f]{7,40}|[[:alnum:]]{52}|[0-9a-f]{64})(\.{2,3})?)+\b'
    ipv4='\b[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b'
    ipv6='\b[0-9a-f]{1,4}(:+([0-9a-f]{1,4})){1,7}\b'
    colors='#[a-f0-9]{6}\b'

    search "($urls|$emails|$hashes|$ipv4|$ipv6|$colors)"
    ;;
esac

exit 0
