#!/bin/bash

case "$1" in
  -l|--last)
    (tmux last-window || tmux next-window || tmux last-pane) &>/dev/null
    exit 0
    ;;
esac

# Forward to vim or a nested tmux session
command=$( tmux display -p '#{pane_current_command}' )
title=$( tmux display -p '#{pane_title}' )
vim=$( tmux display -p '#{@pane-is-vim}' )

if [ "$vim" = 1 ] || [[ "$title" =~  ]] || { [ "$command" = "ssh" ] && [ "${title:0:1}" = "@" ]; }; then
  key=$( echo "${1#-}" | tr 'LDUR' 'hjkl' )
  tmux send-keys "C-$key"

  exit 0
fi

# Forward to tmux
pane=$( tmux display -p '#{pane_index}' )
panes=$( tmux display -p '#{window_panes}' )

if [[ $pane -eq 1 && "$1" =~ ^-[LU]$ ]] ||
   [[ $pane -eq $panes && "$1" =~ ^-[DR]$ ]]; then
  tmux select-pane -P 'bg=#333333'
  sleep 0.03
  tmux select-pane -P bg=default
else
  tmux select-pane "$@"
fi

exit 0
