/etc/inputrc
/etc/profile

/etc/NetworkManager/dispatcher.d/switch-wifi
/etc/ssh/sshd_config.d/dotfiles.conf
/etc/sysctl.d/steamdeck-arp.conf
/etc/systemd/system/sleep.target.wants/steamdeck-switch.service
/etc/systemd/system/steamdeck-switch.service
/etc/udev/rules.d/99-steamdeck-hdmi.rules

/slack/dotfiles
