# Linked to dotfiles
/etc/inputrc
/etc/profile

/etc/atomic-update.conf.d/steamdeck-dotfiles.conf
/etc/NetworkManager/dispatcher.d/switch-wifi
/etc/sysctl.d/steamdeck-arp.conf
/etc/systemd/system/sleep.target.wants/steamdeck-switch.service
/etc/systemd/system/steamdeck-switch.service
/etc/udev/rules.d/99-steamdeck-hdmi.rules

# Manually added
/etc/firewalld/services/*.xml
/etc/firewalld/zones/*.xml
/etc/ssh/sshd_config.d/common.conf
/etc/sudoers.d/common
/etc/systemd/resolved.conf
