/etc/inputrc
/etc/profile

/etc/firewalld/services
/etc/firewalld/zones
/etc/NetworkManager/dispatcher.d/switch-wifi
/etc/ssh/sshd_config.d/dotfiles.conf
/etc/sysctl.d/steamdeck-arp.conf
/etc/udev/rules.d/99-steamdeck-hdmi.rules
