[tools]
# Languages
ruby = "latest"
node = "latest"

# Tools
blender = "latest"
usage = "latest"
yt-dlp = "latest"
"github:dlvhdr/diffnav" = "latest"
"github:TheWaWaR/simple-http-server" = { version = "latest", bin = "simple-http-server" }

[settings]
auto_install = false
not_found_auto_install = false
minimum_release_age = "7d"
env_file = ".env"
lockfile = true

disable_backends = ["asdf"]
disable_hints = ["outdated_bump"]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
compile = false
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
