[tools]
fzf = "0.73.1"
neovim = "0.12.3"
tree-sitter = "0.26.9"
usage = "3.5.0"

[settings]
auto_install = false
not_found_auto_install = false
env_file = ".env"
disable_backends = ["asdf"]
disable_hints = ["outdated_bump"]
minimum_release_age = "7d"

[settings.ruby]
compile = false
