[tools]
# Languages
ruby = "4.0.2"
node = "25.9.0"

# Tools
godot = "4.6.2-stable"
"github:dlvhdr/diffnav" = "0.11.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
