# Reject queries resolving to local IP ranges
stop-dns-rebind

# Allow local queries for .home
rebind-domain-ok=/home/

# Don't cache negative responses
no-negcache

# Don't forward queries for plain names and local IP ranges
domain-needed
bogus-priv
