# Use Quad9 DNS servers
server=9.9.9.9
server=149.112.112.112
server=2620:fe::fe
server=2620:fe::9

# Forward .home queries to router
server=/home/192.168.0.254
server=/0.168.192.in-addr.arpa/192.168.0.254
rebind-domain-ok=/home/

# Reject queries resolving to local IP ranges
stop-dns-rebind

# Don't cache negative responses
no-negcache

# Don't forward queries for plain names and local IP ranges
domain-needed
bogus-priv
